server {
        listen      80 ;
        server_name  pa2hd.com;


        location /  {
            123  ;
        }

        access_log /wls/applogs/nginx/pa2hd.com.access.log main;
        error_log /wls/applogs/nginx/pa2hd.com.error.log warn;
}